<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>OrderWatchLite</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Binance.Net" Version="9.4.0" />
  </ItemGroup>

</Project>
